baseurl: https://barzinm.com
url: https://barzinm.com # http://127.0.0.1:4000/
destination: ./_site

# Site settings
title: Barzin Moridian
description: "Barzin's personal webpage."
paginate: 10
paginate_path: "/blog/page:num/"
first_page_post_count: 5
excerpt_separator: ""

# collections:
#   projects:
#     output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 36c7fe #fed136
  secondary: 025ea2 #36c7fe #fec503
  secondary-dark: 000

# Where things are
# source:       .
# destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
#gems:      [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     /:categories/:year/:title.html
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     2..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    css_class: 'highlight'
    # scope: '.highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
