baseurl: '.' #http://barzinm.com
url: '.' #http://barzinm.com
destination: /home/barzinm/Pets/barzinm.github.io/_site
# Site settings
title: Barzin's Personal Page
description: "Portfolio of Barzin Moridian. Areas of interest: Robotics, Mechatronics, Controls, Machine Learning, and Image processing."
# collections:
#   projects:
#     output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 36c7fe #fed136
  secondary: 025ea2 #36c7fe #fec503
  secondary-dark: 000


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: View LinkedIn Profile
    fa-title: linkedin
    url: https://www.linkedin.com/in/barzinmoridain/
  - title: View GitHub Profile
    fa-title: github
    url: https://github.com/BarzinM
  - title: Go to YouTube Channel
    fa-title: youtube
    url: http://www.youtube.com/playlist?list=PLkMYgm8PFAwYqB8ZoOA1JWI159sfrDKTG


# Postal address (add as many lines as necessary)
address:
  - line: 1400 Townsend Dr.,
  - line: Houghton, MI 49931

# Where things are
# source:       .
# destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
