baseurl: http://barzinm.com
destination: ./_site
keep_files:   [".git", ".svn"]
# Site settings
title: Barzin M
description: "Portfolio of Barzin Moridian. Areas of interest: Robotics, Mechatronics, Controls, Machine Learning, and Image processing."
collections:
  projects:
    output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 36c7fe #fed136
  secondary: 36c7fe #fec503
  secondary-dark: 000


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: View LinkedIn Profile
    fa-title: linkedin
    url: https://www.linkedin.com/in/barzinmoridain/
  - title: View GitHub Profile
    fa-title: github
    url: https://github.com/BarzinM
  - title: Go to YouTube Channel
    fa-title: youtube
    url: http://www.youtube.com/playlist?list=PLkMYgm8PFAwYqB8ZoOA1JWI159sfrDKTG


# Postal address (add as many lines as necessary)
address:
  - line: 1400 Townsend Dr.,
  - line: Houghton, MI 49931

# Build settings
permalink: pretty
markdown: kramdown
highlighter: pygments
future: true
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  use_coderay: true

  coderay:
    coderay_line_numbers: table
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

